### ISSUE TITLE
install fails with "no go-import meta tags"

### ISSUE THREAD

**Issue by Andy2244** [darkfeline/animanager-go#1]
I'm just getting this with a fresh go install?

```
go get -u go.felesatra.moe/animanager
package go.felesatra.moe/animanager: unrecognized import path "go.felesatra.moe/animanager": parse https://go.felesatra.moe/animanager?go-get=1: no go-import meta tags ()
```
```
go version
go version go1.15 windows/amd64
```

**Comment by Andy2244** [comment]
oki this was with the main golang installer from chocolatey. 
I'm kinda new to go, but seems its because the installer set `GOPATH=C:\Users\andy\go`, without setting also `GO111MODULE=on`?
I manually set this variable and then got it working via `go get -u go.felesatra.moe/animanager`

So this should be added to the readme and chagned to:

`GO111MODULE=on go get -u go.felesatra.moe/animanager`

**Comment by darkfeline** [comment]
Go modules are on by default.  I'm not familiar with Windows, but it sounds like chocolatey is super out of date, which is not my problem.  I won't do anything since I doubt I will get more people asking this question before chocolatey fixes it (and if chocolatey doesn't fix it, then I would recommend people to not use it because it's clearly not maintained well).

Edit: Re-reading the top post, I misunderstood the issue.  It sounds like a bug in how Go handles go-import meta tags for modules.

**Comment by darkfeline** [comment]
Filed https://github.com/golang/go/issues/40883
